### ISSUE TITLE
Slow Clone Method

### ISSUE THREAD

**Issue by FrediBach** [floating/restore#1]
Your JSON stringify clone method could be improved greatly. Have a look at this benchmark: http://jsben.ch/bWfk9

Beside that, nice library.

**Comment by floating** [comment]
I've updated the clone method to...
```javascript
const clone = o => {
  let n, i
  if (typeof o !== 'object') return o
  if (!o) return o
  if (o.constructor === Array) {
    n = []
    for (i = 0; i < o.length; i++) n[i] = clone(o[i])
    return n
  }
  n = {}
  for (i in o) n[i] = clone(o[i])
  return n
}
```
Which seems to be the most preformant deep copy option https://jsperf.com/deep-copy-vs-json-stringify-json-parse/51
