### ISSUE TITLE
About Async Updates

### ISSUE THREAD

**Issue by ciro-maciel** [floating/restore#13]
Interesting your project

How do you advise structured async updates?

--
Ciro

**Comment by floating** [comment]
Hey Ciro, thanks for your interest in the project.

Actions can contain synchronous and asynchronous updates, both are tracked and attributed to the action throughout its lifecycle. Using the example from the `README` we'll make our `setText` action get the `newText` value from the server and then update the state asynchronously.

``` javascript
export const setText = update => {
  getTextFromServer(newText => {
    update('text', text => newText)
  })
}
```

Many times it can be useful to compose synchronous and asynchronous updates together. Say you wanted to show a loading message while you fetched the `newText` value from the server. You could update a `loading` flag synchronously and then unset it later when you get the response.

``` javascript
export const setText = update => {
  update('loading', loading => true)
  getTextFromServer(newText => {
    update('loading', loading => false)
    update('text', text => newText)
  })
}
```

I hope this is helpful, let me know if you have any other questions. 

Jordan

**Comment by ciro-maciel** [comment]
Thanks Jordan

It was very clear. I will be accompanying the project.

Good work

--
Ciro
